### ISSUE TITLE
Which IMG genomes to download?

### ISSUE THREAD

**Issue by akiledal** [TealFurnholm/Universal-Taxonomy-Database#1]
In the README, step 3 of obtaining IMG data says to:

> Click on each of the categories of genomes: archaea, bacteria, plasmids, viruses, eukaryotes, and metagenomes

However, there are more options than that which should probably be specified to make sure that the correct data is obtained. For instance, should only isolate genomes be downloaded, or SAGs & MAGs, too? Should only JGI data be exported, or all?

I had a thought that would certainly streamline data retrieval, although at the expense of complicating the scripts. Could all the data be downloaded at once (manually) and then parsed by the script to select the items of interest? For example, when bacterial isolate genomes is clicked on, the URL is https://img.jgi.doe.gov/cgi-bin/mer/main.cgi?section=TaxonList&page=isolateList&domain=Bacteria%20isolates. But, you can modify the URL to https://img.jgi.doe.gov/cgi-bin/mer/main.cgi?section=TaxonList which seems to return all items.

In a similar vein, couldn't the script handle checking that the table columns are in the correct order?

Once last note about the IMG data is that there is no checkbox called `taxon_oid` which I think it refers to `IMG Genome ID (IMG Taxon ID)`?

**Comment by TealFurnholm** [comment]
Hi Anders,

It would be at least if not more difficult to code a script that parses
data we already have to manually obtain, vs just downloading it and
shifting the columns in excel (this is MUCH easier than adding more code!).
I understand wanting to make it automated, completely, but IMG is a
heinously designed website (I mean - they use Excel for downloads!)

You don't need any of the other data types - the first step is  to create a
Taxonomy database - so only things with a taxonomy will be used/useful.

Hopefully you are seeing the below options - I think it will be ok to just
use JGI's IMG ids for Bacteria - otherwise it will take forever.
The archaea, viruses, plasmids, eukaryota and metagenomes (also optional),
you should be able to download without difficulty.

[image: image.png]


Do you have any time to meet Monday? We can see how you are getting on with
the various databases, go over any problems or optimizations.
Did you get past the Taxonomy database scripts?

Have a great weekend.

Best,
Teal
